version: "3.9"

services:
  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/lksdb
      - PORT=3000
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
